### ISSUE TITLE
Formatting on Send to Printer PDF

### ISSUE THREAD

**Issue by davidamichelson** [srophe/e-gedsh#223]
The send to printer PDF button (javascript:window.print) is great and if it can't be easily tweeked should be left as is. But if it can there are two small glitches based on this example: http://wwwb.library.vanderbilt.edu/exist/apps/e-gedsh/entry.html?id=http://gedsh.bethmardutho.org/Antioch

See this PDF
[Antioch.pdf](https://github.com/srophe/e-gedsh/files/1943271/Antioch.pdf)

Both glitches are on page two:

The URL in the header of the page is printing over the first line of text on page two. Can you set the header to be wider?

Further down on page two there appear to be an image of text that says "Click to send this page to the printer" Can you suppress that. It appears to be an image not live text.

Thanks

**Comment by wsalesky** [comment]
Fixed

**Comment by davidamichelson** [comment]
You are too good at what you do.

**Comment by davidamichelson** [comment]
Oops one more but only if it is easy to change. The embeded links in the PDFS show their link paths (eg.  (/exist/apps/e-gedsh/entry/al-Anbar) | Antioch |  (/exist/apps/e-gedsh/entry/Antun-of-Tagrit) or (Beth Lapaṭ (/exist/apps/e-gedsh/entry/Beth-Lapat)). Could these paths be hidden please?

**Comment by wsalesky** [comment]
@davidamichelson Can you try a hard refresh? I thought I hid those with the most recent change

**Comment by davidamichelson** [comment]
I think you hid them in the head of the article but in the body of the article the /exist/apps/e-gedsh/entry/ still appears for me.

**Comment by wsalesky** [comment]
No links in the print? Or no internal links?

**Comment by wsalesky** [comment]
@davidamichelson  How about now?

**Comment by davidamichelson** [comment]
Fixed! Thanks!

**Comment by davidamichelson** [comment]
@dlschwartz Do you mind that winona removed the links in the PDF? It fixed a glitch and looks better. One thing that is lost is the cross references, but those are of less value in a PDF anyway, so I think it is fine.

**Comment by dlschwartz** [comment]
Looking better is the goal, I think. We cannot and shouldn't try to make a printout of all we get from the full electronic edition.

**Comment by wsalesky** [comment]
@dlschwartz Can this be closed?

**Comment by dlschwartz** [comment]
Yes! I'll close it. Thanks.
